### ISSUE TITLE
Can't download Java(anymore)

### ISSUE THREAD

**Issue by andreyrusanov** [sleighzy/ansible-java-8#1]
It worked perfectly before, but today I got an error:
```
TASK [sleighzy.java-8 : Download Java JDK] *************************************
fatal: [X.X.X.X]: FAILED! => {"changed": false, "dest": "/tmp/jdk-8u102-linux-x64.tar.gz", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz"}
```
I also can't download archive manually from "http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz"

**Comment by sleighzy** [comment]
My apologies for that, Oracle had released a later version and removed the download link for the previous tar package. I have updated the role default variables to reflect the latest download url so this will work fine for you again now.

If you have future issues with version changes please let me know, in the short-term you can also update the role default values to reference new download urls. Just visit the Oracle site and after accepting the license agreement copy the download link for the Linux x64 tar.gz file. You can use that link for the "java_download_url" role variable and also update the "java_archive_name" and "java_jdk_dir" appropriately.

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by andreyrusanov** [comment]
It works now! Thank you for the quick update.
